//    General Reducer
export const GENERAL_REQUEST = 'GENERAL_REQUEST'
export const GENERAL_FAILED = 'GENERAL_FAILED'
export const GENERAL_RESET = 'GENERAL_RESET'

export const SET_SIDE_BAR = 'SET_SIDE_BAR'
export const SET_SIDE_FOLD = 'SET_SIDE_FOLD'
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS'
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS'

//    Auth Reducer
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_RESET = 'AUTH_RESET'

export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT'
export const USER_OTP_SUCCESS = 'USER_OTP_SUCCESS'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
